/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://aea2unmxybcb5kvfwbgzfmqjuq.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mxjwd4gclngind4xrqtlmxjnu4",
    "aws_cognito_identity_pool_id": "ap-south-1:30e5a25a-e5a0-49bd-9216-59a7f3fba10b",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_3pHk3Awb3",
    "aws_user_pools_web_client_id": "2amauo50pl8u3m49q3jmufr7tg",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
